url: "http://lyon.afup.org"

title: "AFUP Lyon"
description: >-
  Antenne AFUP Lyon
twitter_username: AFUP_Lyon
meetup_url: "https://www.meetup.com/fr-FR/afup-lyon-php/"

permalink: /posts/:title

ga_ua: "G-KRC2L7ZCZC"
home_featured_articles_count: 2

subheader:
  - label: AFUP DAY 2024
    url: "https://event.afup.org"
    icon: calendar
  - label: Appel Ã  speakers
    url: "/cfp"
    icon: bullhorn
  - label: "Historique"
    url: "/historique"
    icon: landmark

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
   - Makefile
   - docker-compose.yml
   - docker-compose.override.yml-dist
   - docker-compose.override.yml
   - Gemfile
   - Gemfile.lock

feed:
  path: feed

